# Generated by Django 5.2.7 on 2025-10-26 01:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FavoriteMovie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tmdb_id', models.IntegerField(unique=True)),
                ('title', models.CharField(max_length=255)),
                ('overview', models.TextField()),
                ('release_date', models.CharField(blank=True, max_length=20, null=True)),
                ('poster_path', models.CharField(blank=True, max_length=255, null=True)),
                ('vote_average', models.FloatField(default=0)),
            ],
        ),
    ]
